# Generated by Django 5.0.1 on 2024-01-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
