# Generated by Django 5.0.1 on 2024-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In_progress'), ('paused', 'Paused')], default='in_progress', max_length=20),
        ),
    ]
