# Generated by Django 5.0.1 on 2024-02-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_goal_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Goal_Users',
        ),
    ]
