# Generated by Django 5.0.1 on 2024-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_users_goal_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_users',
            name='first_name',
            field=models.CharField(help_text='Enter your first name', max_length=30),
        ),
    ]
